export const array_typed_disabled_values = []
export const array_typed_values = [
	"another_realm(`new (class BigInt64ArrayEx extends BigInt64Array {})()`)",
	"another_realm(`new (class extends BigInt64Array {})()`)",
	"another_realm(`new (class BigUint64ArrayEx extends BigUint64Array {})()`)",
	"another_realm(`new (class extends BigUint64Array {})()`)",
	"another_realm(`new (class Float32ArrayEx extends Float32Array {})()`)",
	"another_realm(`new (class extends Float32Array {})()`)",
	"another_realm(`new (class Float64ArrayEx extends Float64Array {})()`)",
	"another_realm(`new (class extends Float64Array {})()`)",
	"another_realm(`new (class Int16ArrayEx extends Int16Array {})()`)",
	"another_realm(`new (class extends Int16Array {})()`)",
	"another_realm(`new (class Int32ArrayEx extends Int32Array {})()`)",
	"another_realm(`new (class extends Int32Array {})()`)",
	"another_realm(`new (class Int8ArrayEx extends Int8Array {})()`)",
	"another_realm(`new (class extends Int8Array {})()`)",
	"another_realm(`new (class Uint16ArrayEx extends Uint16Array {})()`)",
	"another_realm(`new (class extends Uint16Array {})()`)",
	"another_realm(`new (class Uint32ArrayEx extends Uint32Array {})()`)",
	"another_realm(`new (class extends Uint32Array {})()`)",
	"another_realm(`new (class Uint8ArrayEx extends Uint8Array {})()`)",
	"another_realm(`new (class extends Uint8Array {})()`)",
	"another_realm(`new (class Uint8ClampedArrayEx extends Uint8ClampedArray {})()`)",
	"another_realm(`new (class extends Uint8ClampedArray {})()`)",
	"another_realm(`new BigInt64Array()`)",
	"another_realm(`new BigInt64Array`)",
	"another_realm(`new BigUint64Array()`)",
	"another_realm(`new BigUint64Array`)",
	"another_realm(`new Float32Array()`)",
	"another_realm(`new Float32Array`)",
	"another_realm(`new Float32Array(1)`)",
	"another_realm(`new Float64Array()`)",
	"another_realm(`new Float64Array`)",
	"another_realm(`new Int16Array()`)",
	"another_realm(`new Int16Array`)",
	"another_realm(`new Int32Array()`)",
	"another_realm(`new Int32Array`)",
	"another_realm(`new Int8Array()`)",
	"another_realm(`new Int8Array`)",
	"another_realm(`new Uint16Array()`)",
	"another_realm(`new Uint16Array`)",
	"another_realm(`new Uint32Array()`)",
	"another_realm(`new Uint32Array`)",
	"another_realm(`new Uint8Array()`)",
	"another_realm(`new Uint8Array`)",
	"another_realm(`new Uint8ClampedArray()`)",
	"another_realm(`new Uint8ClampedArray`)",
	"new (class BigInt64ArrayEx extends BigInt64Array {})()",
	"new (class extends BigInt64Array {})()",
	"new (class BigUint64ArrayEx extends BigUint64Array {})()",
	"new (class extends BigUint64Array {})()",
	"new (class Float32ArrayEx extends Float32Array {})()",
	"new (class extends Float32Array {})()",
	"new (class Float64ArrayEx extends Float64Array {})()",
	"new (class extends Float64Array {})()",
	"new (class Int16ArrayEx extends Int16Array {})()",
	"new (class extends Int16Array {})()",
	"new (class Int32ArrayEx extends Int32Array {})()",
	"new (class extends Int32Array {})()",
	"new (class Int8ArrayEx extends Int8Array {})()",
	"new (class extends Int8Array {})()",
	"new (class Uint16ArrayEx extends Uint16Array {})()",
	"new (class extends Uint16Array {})()",
	"new (class Uint32ArrayEx extends Uint32Array {})()",
	"new (class extends Uint32Array {})()",
	"new (class Uint8ArrayEx extends Uint8Array {})()",
	"new (class extends Uint8Array {})()",
	"new (class Uint8ClampedArrayEx extends Uint8ClampedArray {})()",
	"new (class extends Uint8ClampedArray {})()",
	"new BigInt64Array()",
	"new BigInt64Array",
	"new BigUint64Array()",
	"new BigUint64Array",
	"new Float32Array()",
	"new Float32Array",
	"new Float32Array(1)",
	"new Float64Array()",
	"new Float64Array",
	"new Int16Array()",
	"new Int16Array",
	"new Int32Array()",
	"new Int32Array",
	"new Int8Array()",
	"new Int8Array",
	"new Uint16Array()",
	"new Uint16Array",
	"new Uint32Array()",
	"new Uint32Array",
	"new Uint8Array()",
	"new Uint8Array",
	"new Uint8ClampedArray()",
	"new Uint8ClampedArray"
]