export const boxed_string_disabled_values = []
export const boxed_string_values = [
	"new String(\"   \")",
	"Object(\"   \")",
	"Object(String(\"   \"))",
	"new String()",
	"new String",
	"new String(\"\")",
	"new String([])",
	"Object(\"\")",
	"Object(String())",
	"Object(String(\"\"))",
	"Object(String([]))",
	"new String(\"0\")",
	"new String([0])",
	"Object(\"0\")",
	"Object(String(\"0\"))",
	"Object(String([0]))",
	"new String(\"1\")",
	"new String([1])",
	"Object(\"1\")",
	"Object(String(\"1\"))",
	"Object(String([1]))",
	"new String(null)",
	"new String(undefined)",
	"new String(true)",
	"new String(false)",
	"new String(\"str\")",
	"new String(\"NaN\")",
	"new String(new Array(2))",
	"new String(/a/)",
	"Object(\"str\")",
	"Object(\"NaN\")",
	"Object(Date())",
	"Object(String(null))",
	"Object(String(undefined))",
	"Object(String(true))",
	"Object(String(false))",
	"Object(String(\"str\"))",
	"Object(String(\"NaN\"))",
	"Object(String(new Array(2)))",
	"Object(String(/a/))",
	"another_realm(`new String(\"   \")`)",
	"another_realm(`Object(\"   \")`)",
	"another_realm(`Object(String(\"   \"))`)",
	"another_realm(`new String()`)",
	"another_realm(`new String`)",
	"another_realm(`new String(\"\")`)",
	"another_realm(`new String([])`)",
	"another_realm(`Object(\"\")`)",
	"another_realm(`Object(String())`)",
	"another_realm(`Object(String(\"\"))`)",
	"another_realm(`Object(String([]))`)",
	"another_realm(`new String(\"0\")`)",
	"another_realm(`new String([0])`)",
	"another_realm(`Object(\"0\")`)",
	"another_realm(`Object(String(\"0\"))`)",
	"another_realm(`Object(String([0]))`)",
	"another_realm(`new String(\"1\")`)",
	"another_realm(`new String([1])`)",
	"another_realm(`Object(\"1\")`)",
	"another_realm(`Object(String(\"1\"))`)",
	"another_realm(`Object(String([1]))`)",
	"another_realm(`new String(null)`)",
	"another_realm(`new String(undefined)`)",
	"another_realm(`new String(true)`)",
	"another_realm(`new String(false)`)",
	"another_realm(`new String(\"str\")`)",
	"another_realm(`new String(\"NaN\")`)",
	"another_realm(`new String(new Array(2))`)",
	"another_realm(`new String(/a/)`)",
	"another_realm(`Object(\"str\")`)",
	"another_realm(`Object(\"NaN\")`)",
	"another_realm(`Object(Date())`)",
	"another_realm(`Object(String(null))`)",
	"another_realm(`Object(String(undefined))`)",
	"another_realm(`Object(String(true))`)",
	"another_realm(`Object(String(false))`)",
	"another_realm(`Object(String(\"str\"))`)",
	"another_realm(`Object(String(\"NaN\"))`)",
	"another_realm(`Object(String(new Array(2)))`)",
	"another_realm(`Object(String(/a/))`)",
	"another_realm(`new (class StringEx extends String {})()`)",
	"another_realm(`new (class extends String {})()`)",
	"new (class StringEx extends String {})()",
	"new (class extends String {})()"
]