export const error_disabled_values = []
export const error_values = [
	"new Error()",
	"new Error",
	"Error()",
	"Error(\"\")",
	"Error(\"str\")",
	"new Error(\"\")",
	"new Error(\"str\")",
	"new EvalError()",
	"new EvalError",
	"EvalError()",
	"new RangeError()",
	"new RangeError",
	"RangeError()",
	"new ReferenceError()",
	"new ReferenceError",
	"ReferenceError()",
	"new SyntaxError()",
	"new SyntaxError",
	"SyntaxError()",
	"new TypeError()",
	"new TypeError",
	"TypeError()",
	"new URIError()",
	"new URIError",
	"URIError()",
	"new WebAssembly.CompileError()",
	"new WebAssembly.CompileError",
	"WebAssembly.CompileError()",
	"new WebAssembly.LinkError()",
	"new WebAssembly.LinkError",
	"WebAssembly.LinkError()",
	"new WebAssembly.RuntimeError()",
	"new WebAssembly.RuntimeError",
	"WebAssembly.RuntimeError()",
	"another_realm(`new AggregateError(\"\")`)",
	"another_realm(`new Error()`)",
	"another_realm(`new EvalError()`)",
	"another_realm(`new RangeError()`)",
	"another_realm(`new ReferenceError()`)",
	"another_realm(`new SyntaxError()`)",
	"another_realm(`new TypeError()`)",
	"another_realm(`new URIError()`)",
	"another_realm(`new WebAssembly.CompileError()`)",
	"another_realm(`new WebAssembly.LinkError()`)",
	"another_realm(`new WebAssembly.RuntimeError()`)",
	"another_realm(`new Error`)",
	"another_realm(`new EvalError`)",
	"another_realm(`new RangeError`)",
	"another_realm(`new ReferenceError`)",
	"another_realm(`new SyntaxError`)",
	"another_realm(`new TypeError`)",
	"another_realm(`new URIError`)",
	"another_realm(`new WebAssembly.CompileError`)",
	"another_realm(`new WebAssembly.LinkError`)",
	"another_realm(`new WebAssembly.RuntimeError`)",
	"another_realm(`Error()`)",
	"another_realm(`EvalError()`)",
	"another_realm(`RangeError()`)",
	"another_realm(`ReferenceError()`)",
	"another_realm(`SyntaxError()`)",
	"another_realm(`TypeError()`)",
	"another_realm(`URIError()`)",
	"another_realm(`WebAssembly.CompileError()`)",
	"another_realm(`WebAssembly.LinkError()`)",
	"another_realm(`WebAssembly.RuntimeError()`)",
	"another_realm(`Error(\"\")`)",
	"another_realm(`Error(\"str\")`)",
	"another_realm(`new Error(\"\")`)",
	"another_realm(`new Error(\"str\")`)",
	"another_realm(`new (class ErrorEx extends Error {})()`)",
	"another_realm(`new (class EvalErrorEx extends EvalError {})()`)",
	"another_realm(`new (class RangeErrorEx extends RangeError {})()`)",
	"another_realm(`new (class ReferenceErrorEx extends ReferenceError {})()`)",
	"another_realm(`new (class SyntaxErrorEx extends SyntaxError {})()`)",
	"another_realm(`new (class TypeErrorEx extends TypeError {})()`)",
	"another_realm(`new (class URIErrorEx extends URIError {})()`)",
	"another_realm(`new (class WebAssembly_CompileErrorEx extends WebAssembly.CompileError {})()`)",
	"another_realm(`new (class WebAssembly_LinkErrorEx extends WebAssembly.LinkError {})()`)",
	"another_realm(`new (class WebAssembly_RuntimeErrorEx extends WebAssembly.RuntimeError {})()`)",
	"another_realm(`new (class extends Error {})()`)",
	"another_realm(`new (class extends EvalError {})()`)",
	"another_realm(`new (class extends RangeError {})()`)",
	"another_realm(`new (class extends ReferenceError {})()`)",
	"another_realm(`new (class extends SyntaxError {})()`)",
	"another_realm(`new (class extends TypeError {})()`)",
	"another_realm(`new (class extends URIError {})()`)",
	"another_realm(`new (class extends WebAssembly.CompileError {})()`)",
	"another_realm(`new (class extends WebAssembly.LinkError {})()`)",
	"another_realm(`new (class extends WebAssembly.RuntimeError {})()`)",
	"another_realm(`new (class AggregateErrorEx extends AggregateError {})(\"\")`)",
	"another_realm(`new (class extends AggregateError {})(\"\")`)",
	"new (class AggregateErrorEx extends AggregateError {})(\"\")",
	"new (class extends AggregateError {})(\"\")",
	"new (class ErrorEx extends Error {})()",
	"new (class extends Error {})()",
	"new (class EvalErrorEx extends EvalError {})()",
	"new (class extends EvalError {})()",
	"new (class RangeErrorEx extends RangeError {})()",
	"new (class extends RangeError {})()",
	"new (class ReferenceErrorEx extends ReferenceError {})()",
	"new (class extends ReferenceError {})()",
	"new (class SyntaxErrorEx extends SyntaxError {})()",
	"new (class extends SyntaxError {})()",
	"new (class TypeErrorEx extends TypeError {})()",
	"new (class extends TypeError {})()",
	"new (class URIErrorEx extends URIError {})()",
	"new (class extends URIError {})()",
	"new (class WebAssembly_CompileErrorEx extends WebAssembly.CompileError {})()",
	"new (class extends WebAssembly.CompileError {})()",
	"new (class WebAssembly_LinkErrorEx extends WebAssembly.LinkError {})()",
	"new (class extends WebAssembly.LinkError {})()",
	"new (class WebAssembly_RuntimeErrorEx extends WebAssembly.RuntimeError {})()",
	"new (class extends WebAssembly.RuntimeError {})()",
	"new AggregateError(\"\")"
]