export const integer_safe_disabled_values = []
export const integer_safe_values = [
	"0",
	"+0",
	"Number()",
	"another_realm(`0`)",
	"another_realm(`+0`)",
	"another_realm(`Number()`)",
	"+1",
	"+1.0",
	"1",
	"Number.MAX_SAFE_INTEGER-1",
	"+Number.MAX_SAFE_INTEGER",
	"another_realm(`+1`)",
	"another_realm(`+1.0`)",
	"another_realm(`1`)",
	"another_realm(`Number.MAX_SAFE_INTEGER-1`)",
	"another_realm(`+Number.MAX_SAFE_INTEGER`)",
	"-0",
	"another_realm(`-0`)",
	"Number.MIN_SAFE_INTEGER",
	"Number.MIN_SAFE_INTEGER+1",
	"-1",
	"another_realm(`Number.MIN_SAFE_INTEGER`)",
	"another_realm(`Number.MIN_SAFE_INTEGER+1`)",
	"another_realm(`-1`)"
]