export const pob_string_blank_disabled_values = []
export const pob_string_blank_values = [
	"\"   \"",
	"String(\"   \")",
	"another_realm(`\"   \"`)",
	"another_realm(`String(\"   \")`)",
	"\"\"",
	"String()",
	"String(\"\")",
	"String([])",
	"another_realm(`\"\"`)",
	"another_realm(`String()`)",
	"another_realm(`String(\"\")`)",
	"another_realm(`String([])`)",
	"new String(\"   \")",
	"Object(\"   \")",
	"Object(String(\"   \"))",
	"new String()",
	"new String",
	"new String(\"\")",
	"new String([])",
	"Object(\"\")",
	"Object(String())",
	"Object(String(\"\"))",
	"Object(String([]))",
	"another_realm(`new String(\"   \")`)",
	"another_realm(`Object(\"   \")`)",
	"another_realm(`Object(String(\"   \"))`)",
	"another_realm(`new String()`)",
	"another_realm(`new String`)",
	"another_realm(`new String(\"\")`)",
	"another_realm(`new String([])`)",
	"another_realm(`Object(\"\")`)",
	"another_realm(`Object(String())`)",
	"another_realm(`Object(String(\"\"))`)",
	"another_realm(`Object(String([]))`)",
	"another_realm(`new (class StringEx extends String {})()`)",
	"another_realm(`new (class extends String {})()`)",
	"new (class StringEx extends String {})()",
	"new (class extends String {})()"
]