export const boxed_primitive_excluding_nil_disabled_values = []
export const boxed_primitive_excluding_nil_values = [
	"new String(\"   \")",
	"Object(\"   \")",
	"Object(String(\"   \"))",
	"new String()",
	"new String",
	"new String(\"\")",
	"new String([])",
	"Object(\"\")",
	"Object(String())",
	"Object(String(\"\"))",
	"Object(String([]))",
	"new String(\"0\")",
	"new String([0])",
	"Object(\"0\")",
	"Object(String(\"0\"))",
	"Object(String([0]))",
	"new String(\"1\")",
	"new String([1])",
	"Object(\"1\")",
	"Object(String(\"1\"))",
	"Object(String([1]))",
	"new String(null)",
	"new String(undefined)",
	"new String(true)",
	"new String(false)",
	"new String(\"str\")",
	"new String(\"NaN\")",
	"new String(new Array(2))",
	"new String(/a/)",
	"Object(\"str\")",
	"Object(\"NaN\")",
	"Object(Date())",
	"Object(String(null))",
	"Object(String(undefined))",
	"Object(String(true))",
	"Object(String(false))",
	"Object(String(\"str\"))",
	"Object(String(\"NaN\"))",
	"Object(String(new Array(2)))",
	"Object(String(/a/))",
	"new Number()",
	"new Number",
	"Object(-0)",
	"Object(0)",
	"Object(+0)",
	"Object(Number())",
	"Object(+Number.MIN_VALUE)",
	"Object(+Number.EPSILON)",
	"Object(+0.1)",
	"Object(+1)",
	"Object(+1.0)",
	"Object(1)",
	"Object(Number.MAX_SAFE_INTEGER-1)",
	"Object(+Number.MAX_SAFE_INTEGER)",
	"Object(+Infinity)",
	"Object(Number.MAX_SAFE_INTEGER+1)",
	"Object(Number.MAX_VALUE-1)",
	"Object(+Number.MAX_VALUE)",
	"Object(Number.MAX_VALUE+1)",
	"Object(-0.1)",
	"Object(-Number.EPSILON)",
	"Object(-Number.MIN_VALUE)",
	"Object(BigInt(-0))",
	"Object(BigInt(0))",
	"Object(BigInt(+0))",
	"Object(-0n)",
	"Object(0n)",
	"Object(Number.MIN_SAFE_INTEGER)",
	"Object(Number.MIN_SAFE_INTEGER+1)",
	"Object(-1)",
	"Object(BigInt(-Number.MAX_VALUE-1))",
	"Object(BigInt(-Number.MAX_VALUE))",
	"Object(BigInt(-Number.MAX_VALUE+1))",
	"Object(BigInt(Number.MIN_SAFE_INTEGER-1))",
	"Object(BigInt(Number.MIN_SAFE_INTEGER))",
	"Object(BigInt(Number.MIN_SAFE_INTEGER+1))",
	"Object(BigInt(-1))",
	"Object(-1n)",
	"Object(-Infinity)",
	"Object(-Number.MAX_VALUE-1)",
	"Object(-Number.MAX_VALUE)",
	"Object(-Number.MAX_VALUE+1)",
	"Object(Number.MIN_SAFE_INTEGER-1)",
	"Object(BigInt(+1))",
	"Object(BigInt(+1.0))",
	"Object(BigInt(1))",
	"Object(BigInt(Number.MAX_SAFE_INTEGER-1))",
	"Object(BigInt(+Number.MAX_SAFE_INTEGER))",
	"Object(1n)",
	"Object(BigInt(Number.MAX_SAFE_INTEGER+1))",
	"Object(BigInt(Number.MAX_VALUE-1))",
	"Object(BigInt(+Number.MAX_VALUE))",
	"Object(BigInt(Number.MAX_VALUE+1))",
	"new Boolean()",
	"new Boolean",
	"Object(false)",
	"Object(Boolean())",
	"Object(NaN)",
	"Object(Symbol())",
	"Object(Symbol(\"\"))",
	"Object(Symbol(\"str\"))",
	"Object(Symbol.for(\"symbol\"))",
	"Object(Symbol.iterator)",
	"Object(true)",
	"Object.freeze(Object(NaN))",
	"another_realm(`new String(\"   \")`)",
	"another_realm(`Object(\"   \")`)",
	"another_realm(`Object(String(\"   \"))`)",
	"another_realm(`new String()`)",
	"another_realm(`new String`)",
	"another_realm(`new String(\"\")`)",
	"another_realm(`new String([])`)",
	"another_realm(`Object(\"\")`)",
	"another_realm(`Object(String())`)",
	"another_realm(`Object(String(\"\"))`)",
	"another_realm(`Object(String([]))`)",
	"another_realm(`new String(\"0\")`)",
	"another_realm(`new String([0])`)",
	"another_realm(`Object(\"0\")`)",
	"another_realm(`Object(String(\"0\"))`)",
	"another_realm(`Object(String([0]))`)",
	"another_realm(`new String(\"1\")`)",
	"another_realm(`new String([1])`)",
	"another_realm(`Object(\"1\")`)",
	"another_realm(`Object(String(\"1\"))`)",
	"another_realm(`Object(String([1]))`)",
	"another_realm(`new String(null)`)",
	"another_realm(`new String(undefined)`)",
	"another_realm(`new String(true)`)",
	"another_realm(`new String(false)`)",
	"another_realm(`new String(\"str\")`)",
	"another_realm(`new String(\"NaN\")`)",
	"another_realm(`new String(new Array(2))`)",
	"another_realm(`new String(/a/)`)",
	"another_realm(`Object(\"str\")`)",
	"another_realm(`Object(\"NaN\")`)",
	"another_realm(`Object(Date())`)",
	"another_realm(`Object(String(null))`)",
	"another_realm(`Object(String(undefined))`)",
	"another_realm(`Object(String(true))`)",
	"another_realm(`Object(String(false))`)",
	"another_realm(`Object(String(\"str\"))`)",
	"another_realm(`Object(String(\"NaN\"))`)",
	"another_realm(`Object(String(new Array(2)))`)",
	"another_realm(`Object(String(/a/))`)",
	"another_realm(`new Number()`)",
	"another_realm(`new Number`)",
	"another_realm(`Object(-0)`)",
	"another_realm(`Object(0)`)",
	"another_realm(`Object(+0)`)",
	"another_realm(`Object(Number())`)",
	"another_realm(`Object(+Number.MIN_VALUE)`)",
	"another_realm(`Object(+Number.EPSILON)`)",
	"another_realm(`Object(+0.1)`)",
	"another_realm(`Object(+1)`)",
	"another_realm(`Object(+1.0)`)",
	"another_realm(`Object(1)`)",
	"another_realm(`Object(Number.MAX_SAFE_INTEGER-1)`)",
	"another_realm(`Object(+Number.MAX_SAFE_INTEGER)`)",
	"another_realm(`Object(+Infinity)`)",
	"another_realm(`Object(Number.MAX_SAFE_INTEGER+1)`)",
	"another_realm(`Object(Number.MAX_VALUE-1)`)",
	"another_realm(`Object(+Number.MAX_VALUE)`)",
	"another_realm(`Object(Number.MAX_VALUE+1)`)",
	"another_realm(`Object(-0.1)`)",
	"another_realm(`Object(-Number.EPSILON)`)",
	"another_realm(`Object(-Number.MIN_VALUE)`)",
	"another_realm(`Object(BigInt(-0))`)",
	"another_realm(`Object(BigInt(0))`)",
	"another_realm(`Object(BigInt(+0))`)",
	"another_realm(`Object(-0n)`)",
	"another_realm(`Object(0n)`)",
	"another_realm(`Object(Number.MIN_SAFE_INTEGER)`)",
	"another_realm(`Object(Number.MIN_SAFE_INTEGER+1)`)",
	"another_realm(`Object(-1)`)",
	"another_realm(`Object(BigInt(-Number.MAX_VALUE-1))`)",
	"another_realm(`Object(BigInt(-Number.MAX_VALUE))`)",
	"another_realm(`Object(BigInt(-Number.MAX_VALUE+1))`)",
	"another_realm(`Object(BigInt(Number.MIN_SAFE_INTEGER-1))`)",
	"another_realm(`Object(BigInt(Number.MIN_SAFE_INTEGER))`)",
	"another_realm(`Object(BigInt(Number.MIN_SAFE_INTEGER+1))`)",
	"another_realm(`Object(BigInt(-1))`)",
	"another_realm(`Object(-1n)`)",
	"another_realm(`Object(-Infinity)`)",
	"another_realm(`Object(-Number.MAX_VALUE-1)`)",
	"another_realm(`Object(-Number.MAX_VALUE)`)",
	"another_realm(`Object(-Number.MAX_VALUE+1)`)",
	"another_realm(`Object(Number.MIN_SAFE_INTEGER-1)`)",
	"another_realm(`Object(BigInt(+1))`)",
	"another_realm(`Object(BigInt(+1.0))`)",
	"another_realm(`Object(BigInt(1))`)",
	"another_realm(`Object(BigInt(Number.MAX_SAFE_INTEGER-1))`)",
	"another_realm(`Object(BigInt(+Number.MAX_SAFE_INTEGER))`)",
	"another_realm(`Object(1n)`)",
	"another_realm(`Object(BigInt(Number.MAX_SAFE_INTEGER+1))`)",
	"another_realm(`Object(BigInt(Number.MAX_VALUE-1))`)",
	"another_realm(`Object(BigInt(+Number.MAX_VALUE))`)",
	"another_realm(`Object(BigInt(Number.MAX_VALUE+1))`)",
	"another_realm(`new Boolean()`)",
	"another_realm(`new Boolean`)",
	"another_realm(`Object(false)`)",
	"another_realm(`Object(Boolean())`)",
	"another_realm(`Object(NaN)`)",
	"another_realm(`Object(Symbol())`)",
	"another_realm(`Object(Symbol(\"\"))`)",
	"another_realm(`Object(Symbol(\"str\"))`)",
	"another_realm(`Object(Symbol.for(\"symbol\"))`)",
	"another_realm(`Object(Symbol.iterator)`)",
	"another_realm(`Object(true)`)",
	"another_realm(`Object.freeze(Object(NaN))`)",
	"another_realm(`new (class BooleanEx extends Boolean {})()`)",
	"another_realm(`new (class extends Boolean {})()`)",
	"another_realm(`new (class NumberEx extends Number {})()`)",
	"another_realm(`new (class extends Number {})()`)",
	"another_realm(`new (class StringEx extends String {})()`)",
	"another_realm(`new (class extends String {})()`)",
	"new (class BooleanEx extends Boolean {})()",
	"new (class extends Boolean {})()",
	"new (class NumberEx extends Number {})()",
	"new (class extends Number {})()",
	"new (class StringEx extends String {})()",
	"new (class extends String {})()"
]