export const class_disabled_values = []
export const class_values = [
	"another_realm(`class A {}`)",
	"another_realm(`class A { fn() {} }`)",
	"another_realm(`class ErrorEx extends Error {}`)",
	"another_realm(`class EvalErrorEx extends EvalError {}`)",
	"another_realm(`class RangeErrorEx extends RangeError {}`)",
	"another_realm(`class ReferenceErrorEx extends ReferenceError {}`)",
	"another_realm(`class SyntaxErrorEx extends SyntaxError {}`)",
	"another_realm(`class TypeErrorEx extends TypeError {}`)",
	"another_realm(`class URIErrorEx extends URIError {}`)",
	"another_realm(`class WebAssembly_CompileErrorEx extends WebAssembly.CompileError {}`)",
	"another_realm(`class WebAssembly_LinkErrorEx extends WebAssembly.LinkError {}`)",
	"another_realm(`class WebAssembly_RuntimeErrorEx extends WebAssembly.RuntimeError {}`)",
	"another_realm(`class AggregateErrorEx extends AggregateError {}`)",
	"another_realm(`class WebAssembly_ModuleEx extends WebAssembly.Module {}`)",
	"another_realm(`class B extends (class A { fn() {} }) { fn() {} }`)",
	"another_realm(`class ObjectEx extends Object {}`)",
	"another_realm(`class FunctionEx extends Function {}`)",
	"another_realm(`class BooleanEx extends Boolean {}`)",
	"another_realm(`class NumberEx extends Number {}`)",
	"another_realm(`class StringEx extends String {}`)",
	"another_realm(`class DateEx extends Date {}`)",
	"another_realm(`class ArrayEx extends Array {}`)",
	"another_realm(`class RegExpEx extends RegExp {}`)",
	"another_realm(`class GeneratorFunctionEx extends GeneratorFunction {}`)",
	"another_realm(`class AsyncGeneratorFunctionEx extends AsyncGeneratorFunction {}`)",
	"another_realm(`class AsyncFunctionEx extends AsyncFunction {}`)",
	"another_realm(`class Intl_CollatorEx extends Intl.Collator {}`)",
	"another_realm(`class Intl_DateTimeFormatEx extends Intl.DateTimeFormat {}`)",
	"another_realm(`class Intl_NumberFormatEx extends Intl.NumberFormat {}`)",
	"another_realm(`class Int8ArrayEx extends Int8Array {}`)",
	"another_realm(`class Uint8ArrayEx extends Uint8Array {}`)",
	"another_realm(`class Uint8ClampedArrayEx extends Uint8ClampedArray {}`)",
	"another_realm(`class Int16ArrayEx extends Int16Array {}`)",
	"another_realm(`class Uint16ArrayEx extends Uint16Array {}`)",
	"another_realm(`class Int32ArrayEx extends Int32Array {}`)",
	"another_realm(`class Uint32ArrayEx extends Uint32Array {}`)",
	"another_realm(`class Float32ArrayEx extends Float32Array {}`)",
	"another_realm(`class Float64ArrayEx extends Float64Array {}`)",
	"another_realm(`class BigInt64ArrayEx extends BigInt64Array {}`)",
	"another_realm(`class BigUint64ArrayEx extends BigUint64Array {}`)",
	"another_realm(`class ArrayBufferEx extends ArrayBuffer {}`)",
	"another_realm(`class SharedArrayBufferEx extends SharedArrayBuffer {}`)",
	"another_realm(`class MapEx extends Map {}`)",
	"another_realm(`class SetEx extends Set {}`)",
	"another_realm(`class WeakMapEx extends WeakMap {}`)",
	"another_realm(`class WeakSetEx extends WeakSet {}`)",
	"another_realm(`class Intl_ListFormatEx extends Intl.ListFormat {}`)",
	"another_realm(`class Intl_PluralRulesEx extends Intl.PluralRules {}`)",
	"another_realm(`class Intl_RelativeTimeFormatEx extends Intl.RelativeTimeFormat {}`)",
	"another_realm(`class BlobEx extends Blob {}`)",
	"another_realm(`class DataViewEx extends DataView {}`)",
	"another_realm(`class WeakRefEx extends WeakRef {}`)",
	"another_realm(`class FinalizationRegistryEx extends FinalizationRegistry {}`)",
	"another_realm(`class PromiseEx extends Promise {}`)",
	"another_realm(`class Intl_LocaleEx extends Intl.Locale {}`)",
	"another_realm(`class Intl_DisplayNamesEx extends Intl.DisplayNames {}`)",
	"another_realm(`class WebAssembly_InstanceEx extends WebAssembly.Instance {}`)",
	"another_realm(`class WebAssembly_MemoryEx extends WebAssembly.Memory {}`)",
	"another_realm(`class WebAssembly_TableEx extends WebAssembly.Table {}`)",
	"another_realm(`class FileEx extends File {}`)",
	"another_realm(`class WorkerEx extends Worker {}`)",
	"another_realm(`class extends Error {}`)",
	"another_realm(`class extends EvalError {}`)",
	"another_realm(`class extends RangeError {}`)",
	"another_realm(`class extends ReferenceError {}`)",
	"another_realm(`class extends SyntaxError {}`)",
	"another_realm(`class extends TypeError {}`)",
	"another_realm(`class extends URIError {}`)",
	"another_realm(`class extends WebAssembly.CompileError {}`)",
	"another_realm(`class extends WebAssembly.LinkError {}`)",
	"another_realm(`class extends WebAssembly.RuntimeError {}`)",
	"another_realm(`class extends AggregateError {}`)",
	"another_realm(`class extends WebAssembly.Module {}`)",
	"another_realm(`class extends Object {}`)",
	"another_realm(`class extends Function {}`)",
	"another_realm(`class extends Boolean {}`)",
	"another_realm(`class extends Number {}`)",
	"another_realm(`class extends String {}`)",
	"another_realm(`class extends Date {}`)",
	"another_realm(`class extends Array {}`)",
	"another_realm(`class extends RegExp {}`)",
	"another_realm(`class extends GeneratorFunction {}`)",
	"another_realm(`class extends AsyncGeneratorFunction {}`)",
	"another_realm(`class extends AsyncFunction {}`)",
	"another_realm(`class extends Intl.Collator {}`)",
	"another_realm(`class extends Intl.DateTimeFormat {}`)",
	"another_realm(`class extends Intl.NumberFormat {}`)",
	"another_realm(`class extends Int8Array {}`)",
	"another_realm(`class extends Uint8Array {}`)",
	"another_realm(`class extends Uint8ClampedArray {}`)",
	"another_realm(`class extends Int16Array {}`)",
	"another_realm(`class extends Uint16Array {}`)",
	"another_realm(`class extends Int32Array {}`)",
	"another_realm(`class extends Uint32Array {}`)",
	"another_realm(`class extends Float32Array {}`)",
	"another_realm(`class extends Float64Array {}`)",
	"another_realm(`class extends BigInt64Array {}`)",
	"another_realm(`class extends BigUint64Array {}`)",
	"another_realm(`class extends ArrayBuffer {}`)",
	"another_realm(`class extends SharedArrayBuffer {}`)",
	"another_realm(`class extends Map {}`)",
	"another_realm(`class extends Set {}`)",
	"another_realm(`class extends WeakMap {}`)",
	"another_realm(`class extends WeakSet {}`)",
	"another_realm(`class extends Intl.ListFormat {}`)",
	"another_realm(`class extends Intl.PluralRules {}`)",
	"another_realm(`class extends Intl.RelativeTimeFormat {}`)",
	"another_realm(`class extends Blob {}`)",
	"another_realm(`class extends DataView {}`)",
	"another_realm(`class extends WeakRef {}`)",
	"another_realm(`class extends FinalizationRegistry {}`)",
	"another_realm(`class extends Promise {}`)",
	"another_realm(`class extends Intl.Locale {}`)",
	"another_realm(`class extends Intl.DisplayNames {}`)",
	"another_realm(`class extends WebAssembly.Instance {}`)",
	"another_realm(`class extends WebAssembly.Memory {}`)",
	"another_realm(`class extends WebAssembly.Table {}`)",
	"another_realm(`class extends File {}`)",
	"another_realm(`class extends Worker {}`)",
	"another_realm(`class {}`)",
	"another_realm(`class { fn() {} }`)",
	"class A {}",
	"class A { fn() {} }",
	"class ErrorEx extends Error {}",
	"class EvalErrorEx extends EvalError {}",
	"class RangeErrorEx extends RangeError {}",
	"class ReferenceErrorEx extends ReferenceError {}",
	"class SyntaxErrorEx extends SyntaxError {}",
	"class TypeErrorEx extends TypeError {}",
	"class URIErrorEx extends URIError {}",
	"class WebAssembly_CompileErrorEx extends WebAssembly.CompileError {}",
	"class WebAssembly_LinkErrorEx extends WebAssembly.LinkError {}",
	"class WebAssembly_RuntimeErrorEx extends WebAssembly.RuntimeError {}",
	"class AggregateErrorEx extends AggregateError {}",
	"class WebAssembly_ModuleEx extends WebAssembly.Module {}",
	"class B extends (class A { fn() {} }) { fn() {} }",
	"class ObjectEx extends Object {}",
	"class FunctionEx extends Function {}",
	"class BooleanEx extends Boolean {}",
	"class NumberEx extends Number {}",
	"class StringEx extends String {}",
	"class DateEx extends Date {}",
	"class ArrayEx extends Array {}",
	"class RegExpEx extends RegExp {}",
	"class GeneratorFunctionEx extends GeneratorFunction {}",
	"class AsyncGeneratorFunctionEx extends AsyncGeneratorFunction {}",
	"class AsyncFunctionEx extends AsyncFunction {}",
	"class Intl_CollatorEx extends Intl.Collator {}",
	"class Intl_DateTimeFormatEx extends Intl.DateTimeFormat {}",
	"class Intl_NumberFormatEx extends Intl.NumberFormat {}",
	"class Int8ArrayEx extends Int8Array {}",
	"class Uint8ArrayEx extends Uint8Array {}",
	"class Uint8ClampedArrayEx extends Uint8ClampedArray {}",
	"class Int16ArrayEx extends Int16Array {}",
	"class Uint16ArrayEx extends Uint16Array {}",
	"class Int32ArrayEx extends Int32Array {}",
	"class Uint32ArrayEx extends Uint32Array {}",
	"class Float32ArrayEx extends Float32Array {}",
	"class Float64ArrayEx extends Float64Array {}",
	"class BigInt64ArrayEx extends BigInt64Array {}",
	"class BigUint64ArrayEx extends BigUint64Array {}",
	"class ArrayBufferEx extends ArrayBuffer {}",
	"class SharedArrayBufferEx extends SharedArrayBuffer {}",
	"class MapEx extends Map {}",
	"class SetEx extends Set {}",
	"class WeakMapEx extends WeakMap {}",
	"class WeakSetEx extends WeakSet {}",
	"class Intl_ListFormatEx extends Intl.ListFormat {}",
	"class Intl_PluralRulesEx extends Intl.PluralRules {}",
	"class Intl_RelativeTimeFormatEx extends Intl.RelativeTimeFormat {}",
	"class BlobEx extends Blob {}",
	"class DataViewEx extends DataView {}",
	"class WeakRefEx extends WeakRef {}",
	"class FinalizationRegistryEx extends FinalizationRegistry {}",
	"class PromiseEx extends Promise {}",
	"class Intl_LocaleEx extends Intl.Locale {}",
	"class Intl_DisplayNamesEx extends Intl.DisplayNames {}",
	"class WebAssembly_InstanceEx extends WebAssembly.Instance {}",
	"class WebAssembly_MemoryEx extends WebAssembly.Memory {}",
	"class WebAssembly_TableEx extends WebAssembly.Table {}",
	"class FileEx extends File {}",
	"class WorkerEx extends Worker {}",
	"class extends Error {}",
	"class extends EvalError {}",
	"class extends RangeError {}",
	"class extends ReferenceError {}",
	"class extends SyntaxError {}",
	"class extends TypeError {}",
	"class extends URIError {}",
	"class extends WebAssembly.CompileError {}",
	"class extends WebAssembly.LinkError {}",
	"class extends WebAssembly.RuntimeError {}",
	"class extends AggregateError {}",
	"class extends WebAssembly.Module {}",
	"class extends Object {}",
	"class extends Function {}",
	"class extends Boolean {}",
	"class extends Number {}",
	"class extends String {}",
	"class extends Date {}",
	"class extends Array {}",
	"class extends RegExp {}",
	"class extends GeneratorFunction {}",
	"class extends AsyncGeneratorFunction {}",
	"class extends AsyncFunction {}",
	"class extends Intl.Collator {}",
	"class extends Intl.DateTimeFormat {}",
	"class extends Intl.NumberFormat {}",
	"class extends Int8Array {}",
	"class extends Uint8Array {}",
	"class extends Uint8ClampedArray {}",
	"class extends Int16Array {}",
	"class extends Uint16Array {}",
	"class extends Int32Array {}",
	"class extends Uint32Array {}",
	"class extends Float32Array {}",
	"class extends Float64Array {}",
	"class extends BigInt64Array {}",
	"class extends BigUint64Array {}",
	"class extends ArrayBuffer {}",
	"class extends SharedArrayBuffer {}",
	"class extends Map {}",
	"class extends Set {}",
	"class extends WeakMap {}",
	"class extends WeakSet {}",
	"class extends Intl.ListFormat {}",
	"class extends Intl.PluralRules {}",
	"class extends Intl.RelativeTimeFormat {}",
	"class extends Blob {}",
	"class extends DataView {}",
	"class extends WeakRef {}",
	"class extends FinalizationRegistry {}",
	"class extends Promise {}",
	"class extends Intl.Locale {}",
	"class extends Intl.DisplayNames {}",
	"class extends WebAssembly.Instance {}",
	"class extends WebAssembly.Memory {}",
	"class extends WebAssembly.Table {}",
	"class extends File {}",
	"class extends Worker {}",
	"class {}",
	"class { fn() {} }"
]