export const weak_disabled_values = []
export const weak_values = [
	"another_realm(`new (class WeakMapEx extends WeakMap {})()`)",
	"another_realm(`new (class extends WeakMap {})()`)",
	"another_realm(`new (class WeakRefEx extends WeakRef {})({})`)",
	"another_realm(`new (class extends WeakRef {})({})`)",
	"another_realm(`new (class WeakSetEx extends WeakSet {})()`)",
	"another_realm(`new (class extends WeakSet {})()`)",
	"another_realm(`new WeakMap()`)",
	"another_realm(`new WeakMap`)",
	"another_realm(`new WeakRef({})`)",
	"another_realm(`new WeakSet()`)",
	"another_realm(`new WeakSet`)",
	"new (class WeakMapEx extends WeakMap {})()",
	"new (class extends WeakMap {})()",
	"new (class WeakRefEx extends WeakRef {})({})",
	"new (class extends WeakRef {})({})",
	"new (class WeakSetEx extends WeakSet {})()",
	"new (class extends WeakSet {})()",
	"new WeakMap()",
	"new WeakMap",
	"new WeakRef({})",
	"new WeakSet()",
	"new WeakSet"
]